sudo: required

services:
  - docker

before_install:
 - docker build -f "./client/Dockerfile.dev" "./client" -t ayoub/multitest

script:
  - docker run -e CI=true ayoub/multitest npm run test -- --coverage

after_success:
  - docker build -t sinchi/multi-client ./client
  - docker build -t sinchi/multi-nginx ./nginx
  - docker build -t sinchi/multi-server ./server
  - docker build -t sinchi/multi-worker ./worker
 
  # login to dockerhub to
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push image to dockerhub
  - docker push sinchi/multi-client
  - docker push sinchi/multi-nginx
  - docker push sinchi/multi-server
  - docker push sinchi/multi-worker

